version: "3"

services:
  nuxt:
    build: ./
    container_name: carsell-website
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx:
    image: nginx:latest
    container_name: carsell-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nuxt
